name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest

    - name: Build executables
      run: |
        if ("${{ matrix.os }}" -eq "windows-latest") {
          pyinstaller --noconfirm --onedir --windowed --icon "./icon/H_check.ico" --name "EM-Manager" --add-data "./ui;ui/" --add-data "./test;test/" --add-data "./icon;icon/" --collect-all "graphviz" --collect-all "networkx" --collect-all "pyvista" --collect-all "pyvistaqt" --add-data "./parser;parser/" --add-data "./modules;modules/" --add-data "./template;template/" --add-data "./help;help/"  "./EDMatrix2Graphml.py"
        }
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: EM-Manager
        path: dist/*
