name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-docx
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest

    - name: Build executables
      run: |
        if ("${{ matrix.os }}" -eq "windows-latest") {
          pyinstaller --noconfirm --onedir --windowed --icon "icon/H_check.ico" --name "EM-Manager" --add-data "ui:ui" --add-data "icon:icon" --add-data "parser:parser" --add-data "modules:modueles" --add-data "template:template" --add-data "help:help" --add-data "test:test" --add-data "./EDMatrix2Graphml.py;." --collect-all "graphviz" --collect-all "pyautogui" --collect-all "networkx" --collect-all "pyvista" --collect-all "pyvistaqt" --collect-all "pyqtgraph" "EDMatrix2Graphml.py"
        }

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: EM-Manager
        path: dist/*
